name: notifications
description: "A new Flutter package project."
version: 0.0.1

publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../core
  fluttertoast: ^8.2.4
  firebase_messaging: ^14.7.16
  flutter_local_notifications: ^16.3.2
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  injectable:
    git:
      url: https://github.com/FelixZY/injectable.git
      path: injectable
      ref: fix-singleton-environment-filter
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  retrofit_generator: ^8.0.6
  # injectable_generator: ^2.4.1
  injectable_generator:
    git:
      url: https://github.com/FelixZY/injectable.git
      path: injectable_generator
      ref: fix-singleton-environment-filter
  build_runner:
  json_serializable: ^6.7.0

flutter:
  assets: 
    - ../../assets/images/
    - ../../assets/fonts/
    - ../../assets/lottie/
    - ../../assets/svg/
    - ../../assets/translations/
  # fonts:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
