name: driver_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ### Core
  equatable: ^2.0.3
  dartz: ^0.10.1
  auto_size_text: ^3.0.0
  google_fonts: ^6.1.0
  url_launcher: ^6.2.5
  uuid: ^4.3.3

  ### Networking
  retrofit: ^4.1.0
  pretty_dio_logger: ^1.3.1
  dio: ^5.4.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  ### Localization
  easy_localization: ^3.0.3

  ### Locale Storage
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^9.0.0

  ### State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.3

  ### dependency Injection
  get_it: ^7.6.7
  # injectable: ^2.3.2
  injectable:
    git:
      url: https://github.com/FelixZY/injectable.git
      path: injectable
      ref: fix-singleton-environment-filter

  ### Firebase
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  firebase_storage: ^11.6.4
  firebase_messaging: ^14.7.16
  cloud_firestore: ^4.15.4

  ### UI
  flutter_screenutil: ^5.9.0
  lottie: ^3.0.0
  flutter_phosphor_icons: ^0.0.1+6
  shimmer: ^3.0.0
  flutter_svg: ^2.0.7
  logger: any
  logging: ^1.2.0

  ### Notification
  flutter_local_notifications: ^16.3.2
  

  ### Maps
  latlong2: ^0.9.0
  flutter_map: ^6.1.0
  flutter_map_location_marker: ^8.0.7
  geolocator: ^11.0.0
  maps_toolkit: ^3.0.0
  

### Packages 
  auth:
    path: ../shared/auth/

  home:
    path: ../shared/home/

  core: 
    path: ../shared/core/
  
  driver_map:
    path: packages/driver_map/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

    ### Generators
  freezed: ^2.4.6
  injectable_generator:
    git:
      url: https://github.com/FelixZY/injectable.git
      path: injectable_generator
      ref: fix-singleton-environment-filter
  build_runner:
  json_serializable: ^6.6.2
  retrofit_generator: ^8.0.6

  ### AppIcon
  flutter_launcher_icons: "^0.13.1"
  melos: ^4.1.0

flutter:
  uses-material-design: true

  assets:
    - ../assets/fonts/
    - ../assets/images/
    - ../assets/lottie/
    - ../assets/svg/
    - ../assets/translations/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "../assets/images/black_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  